# Generated by Django 4.1.1 on 2022-11-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MYBOOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mylike', models.CharField(max_length=15, null=True, unique=True)),
                ('mydic', models.CharField(max_length=15, null=True, unique=True)),
                ('myread', models.CharField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MYINFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(null=True, unique=True)),
                ('hp_confirm', models.BooleanField(default=False)),
                ('email_confirm', models.BooleanField(default=False)),
                ('adult_confirm', models.BooleanField(default=False)),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
    ]
