# Generated by Django 4.1.1 on 2023-01-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="COMMENT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply", models.CharField(max_length=100, null=True)),
                ("c_date", models.DateTimeField(auto_now_add=True)),
                ("u_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MYBOOK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MYCHOOSE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Action", models.IntegerField(default=0, null=True)),
                ("Adventure", models.IntegerField(default=0, null=True)),
                ("Animation", models.IntegerField(default=0, null=True)),
                ("Comedy", models.IntegerField(default=0, null=True)),
                ("Crime", models.IntegerField(default=0, null=True)),
                ("Documentary", models.IntegerField(default=0, null=True)),
                ("Drama", models.IntegerField(default=0, null=True)),
                ("Family", models.IntegerField(default=0, null=True)),
                ("Fantasy", models.IntegerField(default=0, null=True)),
                ("History", models.IntegerField(default=0, null=True)),
                ("Horror", models.IntegerField(default=0, null=True)),
                ("Music", models.IntegerField(default=0, null=True)),
                ("Mystery", models.IntegerField(default=0, null=True)),
                ("Romance", models.IntegerField(default=0, null=True)),
                ("ScienceFiction", models.IntegerField(default=0, null=True)),
                ("TVMovie", models.IntegerField(default=0, null=True)),
                ("Thriller", models.IntegerField(default=0, null=True)),
                ("War", models.IntegerField(default=0, null=True)),
                ("Western", models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MYSTAR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.CharField(max_length=15, null=True)),
                ("b_like", models.BooleanField(default=False)),
                ("star", models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
