# Generated by Django 4.1.1 on 2022-11-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='mydic',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='mylike',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='myread',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
