# Generated by Django 4.1.1 on 2022-11-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_alter_mybook_mydic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='mydic',
            field=models.BigIntegerField(null=True),
        ),
    ]
