# Generated by Django 4.1.1 on 2022-11-09 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0005_alter_mybook_mydic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MYCHOOSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.IntegerField(default=0, null=True)),
                ('Adventure', models.IntegerField(default=0, null=True)),
                ('Animation', models.IntegerField(default=0, null=True)),
                ('Comedy', models.IntegerField(default=0, null=True)),
                ('Crime', models.IntegerField(default=0, null=True)),
                ('Documentary', models.IntegerField(default=0, null=True)),
                ('Drama', models.IntegerField(default=0, null=True)),
                ('Family', models.IntegerField(default=0, null=True)),
                ('Fantasy', models.IntegerField(default=0, null=True)),
                ('History', models.IntegerField(default=0, null=True)),
                ('Horror', models.IntegerField(default=0, null=True)),
                ('Music', models.IntegerField(default=0, null=True)),
                ('Mystery', models.IntegerField(default=0, null=True)),
                ('Romance', models.IntegerField(default=0, null=True)),
                ('ScienceFiction', models.IntegerField(default=0, null=True)),
                ('TVMovie', models.IntegerField(default=0, null=True)),
                ('Thriller', models.IntegerField(default=0, null=True)),
                ('War', models.IntegerField(default=0, null=True)),
                ('Western', models.IntegerField(default=0, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
