# Generated by Django 4.1.1 on 2023-03-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_grade_myinfo_regist_myinfo_reg_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myinfo",
            name="regist",
            field=models.BooleanField(default=0),
        ),
    ]
